#mengunakan docker compose versi 2 keatas
version: "3.7"


services:
  item-app:
    image: ilhamatsaris/item-app:v1 #image yg diambil dari akun docker hub
    ports: 
      - "80:8080" #port untuk host 80 dan untuk container 8080
    depends_on:
      - item-db  #itemapp terhubung dengan container item-db    

  item-db:
    image: mongo:3 #mengunakan image mongo ver 3
    volumes:
      - app-db:/data/db # memakai volume app-db target data di container data/db
    restart: always  

volumes:
  app-db: #buat volume bernama app-db